### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ar06x** [OptoCloud/owop-renderer#1]
This is 200x200_-100--100_
![image](https://user-images.githubusercontent.com/45273698/118370121-4269dd00-b574-11eb-9994-85b4dbd2a019.png)

But as you can see, this is not how it actually looks like in owop:
![image](https://user-images.githubusercontent.com/45273698/118370143-5dd4e800-b574-11eb-91a6-a7893f151fc7.png)

**Comment by OptoCloud** [comment]
I'm not sure that I understand what you are having a problem with.

The two images are identical except 2 things:
1. The render produced by owop-renderer is actually 1 pixel per pixel ingame
2. The scrrenshot you took is taken after the render completed so some people has drawn between you rendering and taking the screenshot.

Is there something im overlooking?

**Comment by ar06x** [comment]
> I'm not sure that I understand what you are having a problem with.
> 
> The two images are identical except 2 things:
> 
> 1. The render produced by owop-renderer is actually 1 pixel per pixel ingame
> 2. The scrrenshot you took is taken after the render completed so some people has drawn between you rendering and taking the screenshot.
> 
> Is there something im overlooking?

Yeah lol. It appears that the image is taking what should be on one side (the left) and putting it on the right instead, I think its the first row of chunks but im not sure. Look at where the face is drawn in the two images. Its supposed to be on the left, not the right

**Comment by ar06x** [comment]
👀

**Comment by OptoCloud** [comment]
@wolfy01 Sorry I've been busy with some other stuff lately, I looked into it and fixed it today with the latest commit

**Comment by ar06x** [comment]
Oh nice
